INSERT INTO public.author (birth, first_name, last_name, patronymic) VALUES (null, 'Александр', 'Пушкин', 'Сергеевич');
INSERT INTO public.author (birth, first_name, last_name, patronymic) VALUES (null, 'Михаил', 'Лермонтов', 'Юрьевич');
INSERT INTO public.author (birth, first_name, last_name, patronymic) VALUES (null, 'Федор', 'Тютчев', 'Иванович');
INSERT INTO public.author (birth, first_name, last_name, patronymic) VALUES (null, 'Афанасий', 'Фет', 'Афанасьевич');
INSERT INTO public.author (birth, first_name, last_name, patronymic) VALUES (null, 'Валерий', 'Брюсов', 'Яковлевич');
INSERT INTO public.author (birth, first_name, last_name, patronymic) VALUES (null, 'Иоган', 'Гетте', '');
INSERT INTO public.author (birth, first_name, last_name, patronymic) VALUES (null, 'Александр', 'Грибоедов', '');
INSERT INTO public.author (birth, first_name, last_name, patronymic) VALUES (null, 'Константин', 'Случевский', '');
INSERT INTO public.author (birth, first_name, last_name, patronymic) VALUES (null, 'Томас Лео', 'Клэнси', '');
INSERT INTO public.author (birth, first_name, last_name, patronymic) VALUES (null, 'Уильям', 'Шекспир', '');
INSERT INTO public.title (name) VALUES ( 'Сказки');
INSERT INTO public.title (name) VALUES ( 'Евгений Онегин');
INSERT INTO public.title (name) VALUES ('Герои нашего времени');
INSERT INTO public.title (name) VALUES ( 'Бородино');
INSERT INTO public.title (name) VALUES ( 'Вечер');
INSERT INTO public.title (name) VALUES ( 'В небе тают облака');
INSERT INTO public.title (name) VALUES ( 'Альтер эго');
INSERT INTO public.title (name) VALUES ( 'В лунном сиянии');
INSERT INTO public.title (name) VALUES ( 'Апрель');
INSERT INTO public.title (name) VALUES ('Круги на воде');
INSERT INTO public.title (name) VALUES ( 'На озере');
INSERT INTO public.title (name) VALUES ( 'Дикая роза');
INSERT INTO public.title (name) VALUES ( 'Горе от ума');
INSERT INTO public.title (name) VALUES ( 'Новая страница');
INSERT INTO public.title (name) VALUES ( 'Люблю я в комнате сиянье хрусталей');
INSERT INTO public.title (name) VALUES ( 'Охота за "Красным октябрем"');
INSERT INTO public.title (name) VALUES ('Радуга шесть');
INSERT INTO public.title (name) VALUES ('Ромео и Джульетта');
INSERT INTO public.author_title (authors_id, titles_id) VALUES (1, 1);
INSERT INTO public.author_title (authors_id, titles_id) VALUES (1, 2);
INSERT INTO public.author_title (authors_id, titles_id) VALUES (2, 3);
INSERT INTO public.author_title (authors_id, titles_id) VALUES (2, 4);
INSERT INTO public.author_title (authors_id, titles_id) VALUES (3, 5);
INSERT INTO public.author_title (authors_id, titles_id) VALUES (3, 6);
INSERT INTO public.author_title (authors_id, titles_id) VALUES (4, 7);
INSERT INTO public.author_title (authors_id, titles_id) VALUES (4, 8);
INSERT INTO public.author_title (authors_id, titles_id) VALUES (4, 9);
INSERT INTO public.author_title (authors_id, titles_id) VALUES (5, 10);
INSERT INTO public.author_title (authors_id, titles_id) VALUES (5, 11);
INSERT INTO public.author_title (authors_id, titles_id) VALUES (6, 12);
INSERT INTO public.author_title (authors_id, titles_id) VALUES (7, 13);
INSERT INTO public.author_title (authors_id, titles_id) VALUES (8, 14);
INSERT INTO public.author_title (authors_id, titles_id) VALUES (8, 15);
INSERT INTO public.author_title (authors_id, titles_id) VALUES (9, 16);
INSERT INTO public.author_title (authors_id, titles_id) VALUES (9, 17);
INSERT INTO public.author_title (authors_id, titles_id) VALUES (10, 18);
INSERT INTO public.genre (name) VALUES ('Детям');
INSERT INTO public.genre (name) VALUES ('Роман');
INSERT INTO public.genre (name) VALUES ('Стихи');
INSERT INTO public.genre (name) VALUES ('Рассказ');
INSERT INTO public.genre (name) VALUES ('Пьеса');
INSERT INTO public.genre (name) VALUES ('Трагедия');
INSERT INTO public.title_genre (title_id, genres_id) VALUES (1, 1);
INSERT INTO public.title_genre (title_id, genres_id) VALUES (2, 2);
INSERT INTO public.title_genre (title_id, genres_id) VALUES (3, 2);
INSERT INTO public.title_genre (title_id, genres_id) VALUES (4, 3);
INSERT INTO public.title_genre (title_id, genres_id) VALUES (5, 3);
INSERT INTO public.title_genre (title_id, genres_id) VALUES (6, 3);
INSERT INTO public.title_genre (title_id, genres_id) VALUES (7, 3);
INSERT INTO public.title_genre (title_id, genres_id) VALUES (8, 3);
INSERT INTO public.title_genre (title_id, genres_id) VALUES (9, 3);
INSERT INTO public.title_genre (title_id, genres_id) VALUES (10, 3);
INSERT INTO public.title_genre (title_id, genres_id) VALUES (11, 3);
INSERT INTO public.title_genre (title_id, genres_id) VALUES (12, 3);
INSERT INTO public.title_genre (title_id, genres_id) VALUES (13, 5);
INSERT INTO public.title_genre (title_id, genres_id) VALUES (14, 3);
INSERT INTO public.title_genre (title_id, genres_id) VALUES (15, 3);
INSERT INTO public.title_genre (title_id, genres_id) VALUES (16, 2);
INSERT INTO public.title_genre (title_id, genres_id) VALUES (17, 2);
INSERT INTO public.title_genre (title_id, genres_id) VALUES (18, 6);

INSERT INTO public.client (address, birth, first_name, last_name, patronymic, phone) VALUES ('ул. Пушкина, д.66, кв. 6', '1994-08-29', 'Андрей', 'Миронов', 'Андреевич', '9090909900');
INSERT INTO public.client (address, birth, first_name, last_name, patronymic, phone) VALUES ('ул. Московская, д.72', '1980-01-01', 'Михаил', 'Лоськов', 'Андреевич', '8888888888');
INSERT INTO public.client (address, birth, first_name, last_name, patronymic, phone) VALUES ('ул. Рахманинова, д.321', '1994-01-31', 'Елена', 'Самсонкина', 'Евгеньевна', '9876543210');
INSERT INTO public.client (address, birth, first_name, last_name, patronymic, phone) VALUES ('ул 8 Марта, д. 39, кв. 666', '1995-09-18', 'Алина', 'Чернова', 'Ярославовна', '88005553535');

INSERT INTO public.ticket (closed, datebegin, dateclose, dateend, client_id, history_id, currentticket_id) VALUES (true, '2017-03-11 17:17:30.431000', '2017-03-11 00:00:00.000000', '2017-03-17 00:00:00.000000', 1, 1, null);
INSERT INTO public.ticket (closed, datebegin, dateclose, dateend, client_id, history_id, currentticket_id) VALUES (false, '2017-03-11 17:25:07.152000', null, '2017-03-18 00:00:00.000000', 1, null, 1);
INSERT INTO public.ticket (closed, datebegin, dateclose, dateend, client_id, history_id, currentticket_id) VALUES (false, '2017-03-11 17:25:07.258000', null, '2017-03-20 00:00:00.000000', 1, null, 1);
INSERT INTO public.ticket (closed, datebegin, dateclose, dateend, client_id, history_id, currentticket_id) VALUES (false, '2017-03-11 17:25:44.696000', null, '2017-03-17 00:00:00.000000', 2, null, 2);
INSERT INTO public.ticket (closed, datebegin, dateclose, dateend, client_id, history_id, currentticket_id) VALUES (false, '2017-03-11 17:25:44.714000', null, '2017-03-17 00:00:00.000000', 2, null, 2);

INSERT INTO public.book (available, serial_number, ticket_id, title_id) VALUES (true, 'skz/1', 1, 1);
INSERT INTO public.book (available, serial_number, ticket_id, title_id) VALUES (true, 'skz/2', null, 1);
INSERT INTO public.book (available, serial_number, ticket_id, title_id) VALUES (true, 'skz/3', null, 1);
INSERT INTO public.book (available, serial_number, ticket_id, title_id) VALUES (true, 'skz/4', null, 1);
INSERT INTO public.book (available, serial_number, ticket_id, title_id) VALUES (false, 'evgo/1', 5, 2);
INSERT INTO public.book (available, serial_number, ticket_id, title_id) VALUES (true, 'evgo/2', null, 2);
INSERT INTO public.book (available, serial_number, ticket_id, title_id) VALUES (true, 'evgo/3', null, 2);
INSERT INTO public.book (available, serial_number, ticket_id, title_id) VALUES (true, 'evgo/4', null, 2);
INSERT INTO public.book (available, serial_number, ticket_id, title_id) VALUES (true, 'evgo/5', null, 2);
INSERT INTO public.book (available, serial_number, ticket_id, title_id) VALUES (true, 'skz/5', null, 1);
INSERT INTO public.book (available, serial_number, ticket_id, title_id) VALUES (true, 'alteg/1', null, 7);
INSERT INTO public.book (available, serial_number, ticket_id, title_id) VALUES (true, 'alteg/2', null, 7);
INSERT INTO public.book (available, serial_number, ticket_id, title_id) VALUES (true, 'alteg/3', null, 7);
INSERT INTO public.book (available, serial_number, ticket_id, title_id) VALUES (true, 'alteg/4', null, 7);
INSERT INTO public.book (available, serial_number, ticket_id, title_id) VALUES (true, 'alteg/5', null, 7);
INSERT INTO public.book (available, serial_number, ticket_id, title_id) VALUES (true, 'vluns/1', null, 8);
INSERT INTO public.book (available, serial_number, ticket_id, title_id) VALUES (true, 'vluns/2', null, 8);
INSERT INTO public.book (available, serial_number, ticket_id, title_id) VALUES (true, 'vluns/3', null, 8);
INSERT INTO public.book (available, serial_number, ticket_id, title_id) VALUES (true, 'vluns/4', null, 8);
INSERT INTO public.book (available, serial_number, ticket_id, title_id) VALUES (true, 'vluns/5', null, 8);
INSERT INTO public.book (available, serial_number, ticket_id, title_id) VALUES (true, 'dikr/1', null, 12);
INSERT INTO public.book (available, serial_number, ticket_id, title_id) VALUES (true, 'dikr/2', null, 12);
INSERT INTO public.book (available, serial_number, ticket_id, title_id) VALUES (true, 'dikr/3', null, 12);
INSERT INTO public.book (available, serial_number, ticket_id, title_id) VALUES (true, 'dikr/4', null, 12);
INSERT INTO public.book (available, serial_number, ticket_id, title_id) VALUES (true, 'dikr/5', null, 12);
INSERT INTO public.book (available, serial_number, ticket_id, title_id) VALUES (true, 'lyavk/1', null, 15);
INSERT INTO public.book (available, serial_number, ticket_id, title_id) VALUES (true, 'lyavk/2', null, 15);
INSERT INTO public.book (available, serial_number, ticket_id, title_id) VALUES (true, 'lyavk/3', null, 15);
INSERT INTO public.book (available, serial_number, ticket_id, title_id) VALUES (true, 'lyavk/5', null, 15);
INSERT INTO public.book (available, serial_number, ticket_id, title_id) VALUES (true, 'lyavk/4', null, 15);
INSERT INTO public.book (available, serial_number, ticket_id, title_id) VALUES (true, 'rad6/2', null, 17);
INSERT INTO public.book (available, serial_number, ticket_id, title_id) VALUES (true, 'rad6/4', null, 17);
INSERT INTO public.book (available, serial_number, ticket_id, title_id) VALUES (true, 'rad6/5', null, 17);
INSERT INTO public.book (available, serial_number, ticket_id, title_id) VALUES (true, 'rad6/3', null, 17);
INSERT INTO public.book (available, serial_number, ticket_id, title_id) VALUES (true, 'gnv/1', null, 3);
INSERT INTO public.book (available, serial_number, ticket_id, title_id) VALUES (true, 'gnv/2', null, 3);
INSERT INTO public.book (available, serial_number, ticket_id, title_id) VALUES (true, 'gnv/3', null, 3);
INSERT INTO public.book (available, serial_number, ticket_id, title_id) VALUES (true, 'gnv/4', null, 3);
INSERT INTO public.book (available, serial_number, ticket_id, title_id) VALUES (true, 'gnv/5', null, 3);
INSERT INTO public.book (available, serial_number, ticket_id, title_id) VALUES (true, 'bor/1', null, 4);
INSERT INTO public.book (available, serial_number, ticket_id, title_id) VALUES (true, 'bor/2', null, 4);
INSERT INTO public.book (available, serial_number, ticket_id, title_id) VALUES (true, 'bor/3', null, 4);
INSERT INTO public.book (available, serial_number, ticket_id, title_id) VALUES (true, 'bor/4', null, 4);
INSERT INTO public.book (available, serial_number, ticket_id, title_id) VALUES (true, 'bor/5', null, 4);
INSERT INTO public.book (available, serial_number, ticket_id, title_id) VALUES (true, 'vech/1', null, 5);
INSERT INTO public.book (available, serial_number, ticket_id, title_id) VALUES (true, 'vech/2', null, 5);
INSERT INTO public.book (available, serial_number, ticket_id, title_id) VALUES (true, 'vech/3', null, 5);
INSERT INTO public.book (available, serial_number, ticket_id, title_id) VALUES (true, 'vech/4', null, 5);
INSERT INTO public.book (available, serial_number, ticket_id, title_id) VALUES (true, 'vech/5', null, 5);
INSERT INTO public.book (available, serial_number, ticket_id, title_id) VALUES (true, 'vnto/1', null, 6);
INSERT INTO public.book (available, serial_number, ticket_id, title_id) VALUES (true, 'vnto/2', null, 6);
INSERT INTO public.book (available, serial_number, ticket_id, title_id) VALUES (true, 'vnto/3', null, 6);
INSERT INTO public.book (available, serial_number, ticket_id, title_id) VALUES (true, 'vnto/4', null, 6);
INSERT INTO public.book (available, serial_number, ticket_id, title_id) VALUES (true, 'vnto/5', null, 6);
INSERT INTO public.book (available, serial_number, ticket_id, title_id) VALUES (true, 'apr/1', null, 9);
INSERT INTO public.book (available, serial_number, ticket_id, title_id) VALUES (true, 'apr/2', null, 9);
INSERT INTO public.book (available, serial_number, ticket_id, title_id) VALUES (true, 'apr/3', null, 9);
INSERT INTO public.book (available, serial_number, ticket_id, title_id) VALUES (true, 'apr/4', null, 9);
INSERT INTO public.book (available, serial_number, ticket_id, title_id) VALUES (true, 'apr/5', null, 9);
INSERT INTO public.book (available, serial_number, ticket_id, title_id) VALUES (true, 'krnv/1', null, 10);
INSERT INTO public.book (available, serial_number, ticket_id, title_id) VALUES (true, 'krnv/2', null, 10);
INSERT INTO public.book (available, serial_number, ticket_id, title_id) VALUES (false, 'krnv/4', 3, 10);
INSERT INTO public.book (available, serial_number, ticket_id, title_id) VALUES (true, 'krnv/5', null, 10);
INSERT INTO public.book (available, serial_number, ticket_id, title_id) VALUES (true, 'naoz/1', null, 11);
INSERT INTO public.book (available, serial_number, ticket_id, title_id) VALUES (true, 'naoz/3', null, 11);
INSERT INTO public.book (available, serial_number, ticket_id, title_id) VALUES (true, 'naoz/4', null, 11);
INSERT INTO public.book (available, serial_number, ticket_id, title_id) VALUES (true, 'naoz/5', null, 11);
INSERT INTO public.book (available, serial_number, ticket_id, title_id) VALUES (true, 'gou/1', null, 13);
INSERT INTO public.book (available, serial_number, ticket_id, title_id) VALUES (true, 'gou/2', null, 13);
INSERT INTO public.book (available, serial_number, ticket_id, title_id) VALUES (true, 'gou/3', null, 13);
INSERT INTO public.book (available, serial_number, ticket_id, title_id) VALUES (true, 'gou/4', null, 13);
INSERT INTO public.book (available, serial_number, ticket_id, title_id) VALUES (true, 'gou/5', null, 13);
INSERT INTO public.book (available, serial_number, ticket_id, title_id) VALUES (true, 'nows/1', null, 14);
INSERT INTO public.book (available, serial_number, ticket_id, title_id) VALUES (true, 'nows/2', null, 14);
INSERT INTO public.book (available, serial_number, ticket_id, title_id) VALUES (true, 'nows/3', null, 14);
INSERT INTO public.book (available, serial_number, ticket_id, title_id) VALUES (true, 'nows/4', null, 14);
INSERT INTO public.book (available, serial_number, ticket_id, title_id) VALUES (true, 'nows/5', null, 14);
INSERT INTO public.book (available, serial_number, ticket_id, title_id) VALUES (false, 'redoct/2', 2, 16);
INSERT INTO public.book (available, serial_number, ticket_id, title_id) VALUES (true, 'redoct/3', null, 16);
INSERT INTO public.book (available, serial_number, ticket_id, title_id) VALUES (true, 'redoct/4', null, 16);
INSERT INTO public.book (available, serial_number, ticket_id, title_id) VALUES (false, 'redoct/5', 4, 16);
INSERT INTO public.book (available, serial_number, ticket_id, title_id) VALUES (true, 'rij/1', null, 18);
INSERT INTO public.book (available, serial_number, ticket_id, title_id) VALUES (true, 'rij/2', null, 18);
INSERT INTO public.book (available, serial_number, ticket_id, title_id) VALUES (true, 'rij/3', null, 18);
INSERT INTO public.book (available, serial_number, ticket_id, title_id) VALUES (true, 'rij/4', null, 18);
INSERT INTO public.book (available, serial_number, ticket_id, title_id) VALUES (true, 'rij/5', null, 18);

INSERT INTO public.book_ticket (book_id, ticketshistory_id) VALUES (1, 1);